# - name: Creates directory
#   file:
#     path: ~/backend_app
#     state: directory
---
- name: "update and upgrade packages."
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400
    
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes
    
# - name: Extract the zipped artifact
#   unarchive: 
#     src:  ~/project/artifact.tar.gz
#     dest: ~/

- name: Install dependencies
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm: 
    name: pm2
    global: yes
    production: present

# - name: start pm2
#   command: 
#     cmd: pm2 start npm -- start 
    
- name: Create Backend App Directory
  file:
    path: ~/backend_app_dir
    state: directory
    
- name: "Copy artifact into instances"
  become: true
  copy:
  src: ~/project/artifact.tar.gz
  dest: /home/ubuntu/backend_app_dir/artifact.tar.gz
  
- name: "Start app"
  become: true
  shell: |
   cd /home/ubuntu/backend_app_dir
   tar xzvf artifact.tar.gz
   npm install
   npm run build
   pm2 stop all
   pm2 start npm -- start
   
