---
- name: "update and upgrade packages."
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    
- name: remove unneeded deps
  become: true
  apt:
    autoremove: yes
    
- name: Install dependencies
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: Install pm2
  become: true
  npm: 
    name: pm2
    global: yes
    production: present
    
- name: Create Backend App Directory
  file:
    path: ~/backend_app_dir
    state: directory
    
- name: "Copy artifact into instances"
  become: true
  copy:
   src: ~/project/artifact.tar.gz
   dest: /home/ubuntu/backend_app_dir/artifact.tar.gz
  
- name: "Start app"
  become: true
  shell: |
   cd /home/ubuntu/backend_app_dir
   tar xzvf artifact.tar.gz
   npm install
   npm run build
   pm2 stop all
   pm2 start npm -- start